{"name": "user tries to log in with different failing credentials -- @1.1 ", "status": "passed", "steps": [{"name": "Given I go to start page", "status": "passed", "start": 1609114812096, "stop": 1609114814312}, {"name": "When I click log in button", "status": "passed", "start": 1609114814312, "stop": 1609114816258}, {"name": "When I put my email \"FakeUser\" and password \"<password>\"", "status": "passed", "start": 1609114816258, "stop": 1609114816374}, {"name": "And I confirm the log in", "status": "passed", "start": 1609114816378, "stop": 1609114818610}, {"name": "Then wrong email or password shows up", "status": "passed", "start": 1609114818610, "stop": 1609114818650}, {"name": "And close browser", "status": "passed", "start": 1609114818650, "stop": 1609114819968}], "parameters": [{"name": "username", "value": "FakeUser"}, {"name": "passwor", "value": "FakePasswor"}], "start": 1609114803620, "stop": 1609114819972, "uuid": "a7393624-c8a5-4db0-a046-b3501da2da3b", "historyId": "e508437f2f7dc6a46b1e0650052843ed", "fullName": "features/login.feature:user tries to log in with different failing credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "User logs"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}